#!/bin/bash
set -e 

PATH="/bin:/usr/bin"
OUTPUTDIR=$(mktemp -d)

PLUGINS=( "port_open" "pt_stalk_general" "pt_stalk" "pt_summary" "pt_mysql_summary" "pt_all_summaries" "dummy" "dummy_chain" )
pt_stalk_general=( "pt_summary" "pt_mysql_summary" "pt_stalk" )
dummy_chain=( "dummy" )


function dummy_requirments() {
	return 0;
}

function dummy_run() {
	echo "Hello Percona"
}

function port_open_requirments() {
	if [ -z "$(which ss)" ] && [ -z "$(which netstat)" ]; then
		packageRequired "iproute2"
	fi;

}

function port_open_run() {
	port=${BASH_ARGV[0]}

	if [ $( ss -H -a "( sport = :${port} or dport = :${port} )" | wc -l ) -gt 0 ]; then
		echo "Port $port isn't free";
	else
		echo "Port $port is free"
	fi
}
function pt_summary_requirments() {
	if [ -z "$(which wget)" ]; then
		echo $( packageRequired wget )
		return 1
	fi;

	test -e /tmp/pt-summary || (wget https://www.percona.com/get/pt-summary -O /tmp/pt-summary && chmod 755 /tmp/pt-summary )
}

function pt_summary_run() {
	/tmp/pt-summary
}

function getPlugins() {
	plugin=$1
	local toret=""
	if [ -z "${!plugin}" ]; then
		toret="$toret $plugin"
	else
		tmp="${plugin}[@]"
		for t in "${!tmp}"; do
			if [ -z "{$!t}" ]; then
				toret="$toret $t"
			else
				p=$( getPlugins $t)
				toret="$toret $p"
			fi;
		done;
	fi;

	echo $toret
}

OS=$(lsb_release -s -i)
OSVERSION=$(lsb_release -s -r | cut -f1 -d.)

function usage() {
	echo "Available plugins:"
	for i in ${PLUGINS[@]}; do
		p=$(getPlugins $i)
		if [ "$i" == "$p" ]; then
			echo $i
		else
			echo "$i: $p"
		fi;
	done;
}

test -n "$1" || ( usage; exit 1 )
pluginExists=0	
for plugin in ${PLUGINS[@]}; do
	if [ "$plugin" == "$1" ]; then
		pluginExists=1
	fi
done

if [ "$pluginExists" -eq 0 ]; then
	usage
	exit 1
fi

function packageRequired() {
	 echo "$1 is missing. You can install it with:"
	case $OS in
		"Debian")
			>&2 echo -e "\t apt-get install $1"
			;;
		"CentOS")
			>&2 echo -e "\t yum install $1"
			;;
	esac;
}


set +e


plugin=$(getPlugins $1)

echo "Plugins to run: $plugin"

for p in $plugin; do
	${p}_requirments
	if [ $? -eq 1 ]; then exit 1; fi;
done;

for p in $plugin; do
	echo "Running $p"
	${p}_run | tee $OUTPUTDIR/$p
done;cd 

tar czf /tmp/pt-collect.tar.gz $OUTPUTDIR
#rm -rf $OUTPUTDIR